services:
    vsymfo_panel.form.type.confirmation:
         class: vSymfo\Bundle\PanelBundle\Form\Type\ConfirmationFormType
         tags:
            - { name: form.type }

    vsymfo_panel.service.form_builder:
        class: vSymfo\Bundle\PanelBundle\Service\FormBuilderService
